In [3]:
# log파일 추가 시 한번만 실행
import _common
_common.read_logs()

Reading logs/Huam415-1/251016_SM-S938N_TEST06_n-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST16-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST31_-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST24-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST17-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST07_-M2_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST02_n28-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST09_-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST30_-M2_Fav.xlsx
Reading logs/Huam415-1/251017_SM-S938N_TEST02_N26-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST13_-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST13-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST20-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST14_-M2_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST05_n-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST01_-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST21-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST12-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST06_-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST08_-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST11-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST02_-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST22-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST05_-M1_Fav.xlsx
Reading logs/Huam415-1/251017_SM-S938N_TEST03_N26-M1_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST04_n28-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST10_-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST23-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST18-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST19-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST33_-M1_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST01_n26-M1_Fav.xlsx
Reading logs/Huam415-1/251017_SM-S938N_TEST01_N28-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST04_-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST03_-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST34-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST14-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST35_-M1_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST03_n28-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST32_-M1_Fav.xlsx
Reading logs/Huam415-1/251017_SM-S938N_TEST04_N26-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST15-M2_Fav.xlsx
Reading logs/Huam415-1/251017_SM-S938N_TEST01_N26-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST13_-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST14_-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST13-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST20-M2_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST05_n-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST21-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST01_-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST12-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST06_-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST08_-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST30_-M1_Fav.xlsx
Reading logs/Huam415-1/251017_SM-S938N_TEST04_N28-M1_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST03_n26-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST07_-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST09_-M2_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST04_n26-M1_Fav.xlsx
Reading logs/Huam415-1/251017_SM-S938N_TEST03_N28-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST16-M1_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST06_n-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST31_-M1_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST01_n28-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST24-M1_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST17-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST34-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST14-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST35_-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST32_-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST15-M1_Fav.xlsx
Reading logs/Huam415-1/251017_SM-S938N_TEST02_N28-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST04_-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST03_-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST18-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST33_-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST19-M1_Fav.xlsx
Reading logs/Huam415-1/251016_SM-S938N_TEST02_n26-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST02_-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST11-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST22-M1_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST05_-M2_Fav.xlsx
Reading logs/Huam415-1/251022_SM-S938N_TEST10_-M2_Fav.xlsx
Reading logs/Huam415-1/251024_SM-S938N_TEST23-M2_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST10_M1_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST11_M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST17_-M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST02_-M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST05_-M2_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST08_M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST04_-M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST03_-M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST16_-M2_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST09_M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST18_-M1_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST14_M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST15_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST12_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST07_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST08_-M2_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST06_M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST01_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST06_-M1_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST07_M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST13_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST14_-M1_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST12_M2_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST13_M1_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST08_M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST04_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST03_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST16_-M1_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST09_M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST18_-M2_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST14_M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST17_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST02_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST05_-M1_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST10_M2_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST11_M1_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST12_M1_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST13_M2_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST06_M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST08_-M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST01_-M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST06_-M2_Fav.xlsx
Reading logs/Namsan/251021_SM-S938N_TEST07_M1_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST13_-M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST14_-M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST15_-M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST12_-M2_Fav.xlsx
Reading logs/Namsan/251023_SM-S938N_TEST07_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST24_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST23_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST28_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST38_-M1_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST11_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST26_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST21_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST19_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST02-M1_Fav.xlsx
Reading logs/Huam345-5/251021_SM-S938N_TEST04_M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST42_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST17_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST10_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST40_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST03-M2_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST02_-M2_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST05_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST05_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST02_-M1_Fav.xlsx
Reading logs/Huam345-5/251021_SM-S938N_TEST05_M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST29_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST20_-M1_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST07-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST39_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST27_-M1_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST10_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST33-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST22_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST25_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST32_-M1_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST06-M2_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST04_-M2_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST03_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST03_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST04_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST18_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST11_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST16_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST43_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST12_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST15_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST40_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST07_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST09_-M1_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST10-M2_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST06_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST31_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST36_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST28_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST05-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST21_-M1_Fav.xlsx
Reading logs/Huam345-5/251021_SM-S938N_TEST03_M1_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST08_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST26_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST38_-M1_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST04-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST23_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST24_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST17_TRACE_-M2_Fav.xlsx
Reading logs/Huam345-5/251021_SM-S938N_TEST02_M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST06_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST01_-M2_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST01_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST08_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST16_-M1_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST06_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST34-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST41_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST14_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST13_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST35-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST01-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST25_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST22_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST09-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST37_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST29_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST30_-M2_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST07_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST27_-M1_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST08-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST39_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST20_-M1_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST09_-M2_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST04_-M1_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST03_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST03_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST04_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST18_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST11_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST16_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST43_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST29_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST20_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST07-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST33-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST39_-M2_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST10_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST27_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST22_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST25_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST32_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST06-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST19_-M1_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST02-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST42_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST17_-M2_Fav.xlsx
Reading logs/Huam345-5/251021_SM-S938N_TEST04_M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST10_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST03-M1_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST02_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST40_-M1_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST05_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST05_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST02_-M2_Fav.xlsx
Reading logs/Huam345-5/251021_SM-S938N_TEST05_M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST24_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST23_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST28_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST38_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST26_-M2_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST11_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST21_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST25_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST22_-M1_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST09-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST37_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST29_-M1_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST07_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST30_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST27_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST08-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST39_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST20_-M2_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST09_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST06_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST01_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST08_-M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST16_-M2_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST01_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST34-M2_Fav.xlsx
Reading logs/Huam345-5/251023_SM-S938N_TEST06_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST41_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST14_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST13_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST35-M1_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST01-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST31_-M1_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST06_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST05-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST36_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST28_-M1_Fav.xlsx
Reading logs/Huam345-5/251021_SM-S938N_TEST03_M2_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST21_-M2_Fav.xlsx
Reading logs/Huam345-5/251020_SM-S938N_TEST08_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST26_-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST38_-M2_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST04-M2_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST23_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST24_-M1_Fav.xlsx
Reading logs/Huam345-5/251022_SM-S938N_TEST17_TRACE_-M1_Fav.xlsx
Reading logs/Huam345-5/251021_SM-S938N_TEST02_M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST12_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST15_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST40_-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST07_-M1_Fav.xlsx
Reading logs/Huam345-5/251024_SM-S938N_TEST10-M1_Fav.xlsx
Reading logs/Huam345-5/251027_SM-S938N_TEST09_-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST13-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST20-M1_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST01-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST12-M1_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST09-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST07-M1_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST08-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST06-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST02-M1_Fav.xlsx
Reading logs/Fixed-point/251024_SM-S938N_TEST27_STATIC_-M1_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST10-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST03-M2_Fav.xlsx
Reading logs/Fixed-point/251024_SM-S938N_TEST26_STATIC_-M1_Fav.xlsx
Reading logs/Fixed-point/251024_SM-S938N_TEST25_STATIC_-M1_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST05-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST16-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST17-M1_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST04-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST14-M1_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST07-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST09-M2_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST06-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST15-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST08-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST01-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST05-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST18-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST04-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST19-M2_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST02-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST11-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST10-M2_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST03-M1_Fav.xlsx
Reading logs/Fixed-point/251024_SM-S938N_TEST25_STATIC_-M2_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST05-M2_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST16-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST17-M2_Fav.xlsx
Reading logs/Fixed-point/251105_SM-S938N_TEST04-M1_Fav.xlsx
Reading logs/Fixed-point/251103_SM-S938N_TEST02-M2_Fav.xlsx
Reading logs/Fixed-point/251024_SM-S938N_TEST27_STATIC_-M2_Fav.xlsx

In [5]:
result_path = 'results'
grid_size = 30
sample_min = 30
rb_min = 0

In [2]:
import os
import pandas as pd
import _common, _map, _plot, _dist

df_uhd = _common.read_UHD_xlsx(uhd_dir = 'UHD_Power')

df_grid = _common.grid_uhd(df_uhd, grid_size=grid_size, sample_min=sample_min)
display(df_grid)

df_multi_grid = _common.multi_grid_uhd(df_uhd, grid_size=grid_size, sample_min=sample_min)
display(df_multi_grid)

     lat_bin  lon_bin  uhd_cnt  uhd_avg  uhd_std  uhd_ci95  uhd_max  uhd_min
0     139314   372480       45   -45.87     2.06      0.60   -40.64   -51.31
1     139314   372481      109   -43.67     2.24      0.42   -39.09   -50.48
2     139315   372480      407   -44.63     3.05      0.30   -34.65   -50.58
3     139315   372481      265   -42.45     2.94      0.35   -34.29   -50.79
4     139315   372482      234   -40.19     2.51      0.32   -32.96   -46.23
..       ...      ...      ...      ...      ...       ...      ...      ...
187   139358   372468      139   -34.30     3.18      0.53   -28.43   -40.04
188   139358   372469      169   -38.85     2.21      0.33   -33.46   -43.36
189   139358   372470      145   -40.84     1.61      0.26   -37.18   -43.80
190   139358   372471      176   -37.84     2.88      0.43   -31.06   -42.94
191   139358   372472      117   -34.32     2.92      0.53   -28.29   -40.15

[192 rows x 8 columns]

     lat_bin  lon_bin  uhd_cnt  uhd_avg  uhd_std  uhd_ci95  uhd_max  uhd_min
0     139314   372480       45   -45.87     2.06      0.60   -40.64   -51.31
1     139314   372481      109   -43.67     2.24      0.42   -39.09   -50.48
2     139315   372480      407   -44.63     3.05      0.30   -34.65   -50.58
3     139315   372481      265   -42.45     2.94      0.35   -34.29   -50.79
4     139315   372482      234   -40.19     2.51      0.32   -32.96   -46.23
..       ...      ...      ...      ...      ...       ...      ...      ...
915   139358   372468      176   -36.69     2.72      0.40   -28.43   -42.87
916   139358   372469      145   -40.46     1.65      0.27   -36.03   -43.80
917   139358   372470      168   -39.80     2.15      0.33   -32.91   -43.64
918   139358   372471      160   -35.38     3.51      0.54   -28.29   -42.29
919   139358   372472       52   -34.17     1.86      0.51   -29.99   -37.84

[920 rows x 8 columns]

In [6]:
import os
import pandas as pd
import _common, _map, _plot, _dist
device = 'SM-S938N'

df = _common.analyze_kpi(
    fname = os.path.join("logs",f"{device}.xlsx"),
    date_list = [
        # "251016",
        # "251017",
        # "251020",
        # "251021",
        "251022", # pdcch dynamic 적용
        "251023",
        "251024",
        "251027",
        "251103",
        "251105",
    ],
)
df_map = df[df["route"].isin(['Namsan','Huam415-1','Huam345-5'])].copy()
print()

_common.grid_kpi(device=device, df=df_map, rb_min=rb_min, grid_size=grid_size, sample_min=sample_min)
print()

Reading logs/SM-S938N.xlsx
✅ Read Complete : 98536 lines

⚠️ Locations without UHD Power measurements have been removed (dropped: 19, remaining: 141/160)
📍 [Grid 30m] loc_id Range by Route
──────────────────────────────────────────────
Route        loc_id Range           Counts
──────────────────────────────────────────────
Huam345-5        1 ~ 81                81
Huam415-1       82 ~ 119               38
Namsan         120 ~ 141               22
──────────────────────────────────────────────

✅ Saved: logs/SM-S938N_grid_30m.xlsx

In [7]:
# import os
# import pandas as pd
# import _common, _map, _plot, _dist
# device = 'SM-S938N'

# df = _common.analyze_kpi(
#     fname = os.path.join("logs",f"{device}.xlsx"),
#     date_list = [
#         # "251016",
#         # "251017",
#         # "251020",
#         # "251021",
        
#         # "251022", # pdcch dynamic 적용
#         # "251023",
#         # "251024",
#         # "251027",
#         # "251103",
#         # "251105",
#     ],
# )
# grid_size = 30
# df_grid = pd.read_excel(os.path.join("logs", f"{device}_grid_{grid_size}m.xlsx"))

# out_dir = os.path.join("results", "plot_kpis_each_test")
# _plot.plot_kpis_each_test(df=df, df_grid=df_grid, out_dir=out_dir, grid_size=grid_size)

Reading logs/SM-S938N.xlsx
✅ Read Complete : 98536 lines
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_01.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_02.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_03.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_04.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_05.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_06.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_07.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_08.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_09.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_10.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_13.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_14.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_16.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_17.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_20.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_21.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_22.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_23.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_24.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_25.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_26.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_27.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_28.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_29.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_30.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_31.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_32.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_33.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_34.html
Saved HTML: results/plot_kpis_each_test/251022/Huam415-1/TEST_35.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_38.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_39.html
Saved HTML: results/plot_kpis_each_test/251022/Huam345-5/TEST_40.html
Saved HTML: results/plot_kpis_each_test/251023/Huam345-5/TEST_01.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_01.html
Saved HTML: results/plot_kpis_each_test/251023/Huam345-5/TEST_02.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_02.html
Saved HTML: results/plot_kpis_each_test/251023/Huam345-5/TEST_03.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_03.html
Saved HTML: results/plot_kpis_each_test/251023/Huam345-5/TEST_04.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_04.html
Saved HTML: results/plot_kpis_each_test/251023/Huam345-5/TEST_05.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_05.html
Saved HTML: results/plot_kpis_each_test/251023/Huam345-5/TEST_06.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_06.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_07.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_08.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_12.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_13.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_14.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_15.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_16.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_17.html
Saved HTML: results/plot_kpis_each_test/251023/Namsan/TEST_18.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_01.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_02.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_03.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_04.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_05.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_06.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_07.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_08.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_09.html
Saved HTML: results/plot_kpis_each_test/251024/Huam345-5/TEST_10.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_11.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_12.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_13.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_14.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_15.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_16.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_17.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_18.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_19.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_20.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_21.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_22.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_23.html
Saved HTML: results/plot_kpis_each_test/251024/Huam415-1/TEST_24.html
Saved HTML: results/plot_kpis_each_test/251024/Fixed-point/TEST_25.html
Saved HTML: results/plot_kpis_each_test/251024/Fixed-point/TEST_26.html
Saved HTML: results/plot_kpis_each_test/251024/Fixed-point/TEST_27.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_01.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_02.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_03.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_04.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_05.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_06.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_07.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_08.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_09.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_10.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_11.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_12.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_13.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_14.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_15.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_16.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_17.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_18.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_19.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_20.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_21.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_22.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_23.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_24.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_25.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_26.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_27.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_28.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_29.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_30.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_31.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_32.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_33.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_34.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_35.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_36.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_37.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_38.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_39.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_40.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_41.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_42.html
Saved HTML: results/plot_kpis_each_test/251027/Huam345-5/TEST_43.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_01.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_02.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_03.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_04.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_05.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_06.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_07.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_08.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_09.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_10.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_11.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_12.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_13.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_14.html
Saved HTML: results/plot_kpis_each_test/251103/Fixed-point/TEST_15.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_01.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_02.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_03.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_04.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_05.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_06.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_07.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_08.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_09.html
Saved HTML: results/plot_kpis_each_test/251105/Fixed-point/TEST_10.html

In [7]:
import os
import pandas as pd
import _common, _map, _plot, _dist
device = 'SM-S938N'

# grid가 커질수록 GPS 오차 보정 및 통계적 안정성 향상
# - 이동 속도 약 36 km/h (≈ 10 m/s) 기준, 30m 구간당 약 3개 샘플 수집
# - 동일 루트 10회 이상 반복 시 grid별 30개 이상 샘플 확보 가능
# - 샘플 수 30개 이상이면 중심극한정리(CLT)에 따라 정규분포 근사 가능
# - SINR, Tput 등 고분산 지표의 신뢰구간(CI) 추정에 적합

df_grid = pd.read_excel(os.path.join("logs", f"{device}_grid_{grid_size}m.xlsx"))
out_dir = os.path.join(result_path, "map")

_map.map_coverage(df=df_grid, out_dir=out_dir, grid_size=grid_size, band="n28")
_map.map_uhd_pwr(df=df_grid, out_dir=out_dir, grid_size=grid_size)
_map.map_pct(df=df_grid, out_dir=out_dir, grid_size=grid_size)
_map.map_db(df=df_grid, out_dir=out_dir, grid_size=grid_size)

✅ Saved: results/map/n28_RSRP.html (rows=141)
✅ Saved: results/map/n28_SINR.html (rows=141)
✅ Saved: results/map/n28_DL_Tput.html (rows=141)
✅ Saved: results/map/n28_UHD_pwr_avg.html (rows=141)
✅ Saved: results/map/cmpr_DL_Tput.html (rows=141)
✅ Saved: results/map/cmpr_RSRP.html (rows=141)

In [2]:
import os
import pandas as pd
import _common, _map, _plot, _dist
device = 'SM-S938N'

df_grid = pd.read_excel(os.path.join("logs", f"{device}_grid_{grid_size}m.xlsx"))
out_dir = os.path.join(result_path, "dist", "uhd_pwr")

_dist.dist_uhd_by_minmax(df=df_grid, out_dir=out_dir)
_dist.dist_uhd_by_site(df=df_grid, out_dir=out_dir, grid_size=grid_size)

✅ Saved: results/dist/uhd_pwr/uhd_minmax.html
✅ Saved: results/dist/uhd_pwr/uhd_by_site.html

In [3]:
import os
import pandas as pd
import _common, _map, _plot, _dist
device = 'SM-S938N'

df = _common.analyze_kpi(
    fname = os.path.join("logs",f"{device}.xlsx"),
    date_list = [
        # "251016",
        # "251017",
        # "251020",
        # "251021",
        "251022", # pdcch dynamic 적용
        "251023",
        "251024",
        "251027",
        "251103",
        "251105",
    ],
)
rb_min=0
rsrp_bin=1
sample_min=30
grid_size=30

out_dir = os.path.join("results", "plot")
_plot.plot_kpis_by_site(df=df, out_dir=out_dir, rb_min=rb_min, sample_min=sample_min, rsrp_bin=rsrp_bin)
_plot.plot_kpis_by_band(df=df, out_dir=out_dir, rb_min=rb_min, sample_min=sample_min, rsrp_bin=rsrp_bin)
_plot.plot_kpis_by_uhd(df=df, out_dir=out_dir, rb_min=rb_min, sample_min=sample_min, rsrp_bin=rsrp_bin, grid_size=grid_size)

Reading logs/SM-S938N.xlsx
✅ Read Complete : 98536 lines
✅ Saved: results/plot/kpis_by_site.html
✅ Saved: results/plot/kpis_by_band.html
⚠️ Locations without UHD Power measurements have been removed (dropped: 795, remaining: 40748/41543)
✅ Saved: results/plot/kpis_by_uhd.html

In [4]:
import os
import pandas as pd
import _common, _map, _plot, _dist
device = 'SM-S938N'

df = _common.analyze_kpi(
    fname = os.path.join("logs",f"{device}.xlsx"),
    date_list = [
        # "251016",
        # "251017",
        # "251020",
        # "251021",
        "251022", # pdcch dynamic 적용
        "251023",
        "251024",
        "251027",
        "251103",
        "251105",
    ],
)
rb_min=0
rsrp_bin=1
grid_size=30

out_dir = os.path.join("results", "dist")

_dist.dist_kpis_pdf_by_band(df=df, out_dir=out_dir, rb_min=rb_min)
_dist.dist_kpis_pdf_by_site(df=df, out_dir=out_dir, rb_min=rb_min)
_dist.dist_kpis_pdf_by_uhd(df=df, out_dir=out_dir, rb_min=rb_min, grid_size=grid_size)

# _dist.dist_kpis_cdf_by_band(df=df, out_dir=out_dir, rb_min=rb_min)
# _dist.dist_kpis_cdf_by_site(df=df, out_dir=out_dir, rb_min=rb_min)
# _dist.dist_kpis_cdf_by_uhd(df=df, out_dir=out_dir, rb_min=rb_min, grid_size=grid_size)

_dist.dist_kpis_pdf_rsrp_bins(df=df, out_dir=out_dir, rb_min=rb_min, rsrp_bin=rsrp_bin)

Reading logs/SM-S938N.xlsx
✅ Read Complete : 98536 lines
✅ Saved: results/dist/kpis_pdf_by_band.html
✅ Saved: results/dist/kpis_pdf_by_site.html
⚠️ Locations without UHD Power measurements have been removed (dropped: 2481, remaining: 59484/61965)
✅ Saved: results/dist/kpis_pdf_by_uhd.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-120_to_-119.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-119_to_-118.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-118_to_-117.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-117_to_-116.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-116_to_-115.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-115_to_-114.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-114_to_-113.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-113_to_-112.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-112_to_-111.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-111_to_-110.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-110_to_-109.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-109_to_-108.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-108_to_-107.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-107_to_-106.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-106_to_-105.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-105_to_-104.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-104_to_-103.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-103_to_-102.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-102_to_-101.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-101_to_-100.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-100_to_-99.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-99_to_-98.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-98_to_-97.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-97_to_-96.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-96_to_-95.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-95_to_-94.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-94_to_-93.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-93_to_-92.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-92_to_-91.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-91_to_-90.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-90_to_-89.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-89_to_-88.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-88_to_-87.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-87_to_-86.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-86_to_-85.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-85_to_-84.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-84_to_-83.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-83_to_-82.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-82_to_-81.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-81_to_-80.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-80_to_-79.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-79_to_-78.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-78_to_-77.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-77_to_-76.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-76_to_-75.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-75_to_-74.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-74_to_-73.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-73_to_-72.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-72_to_-71.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-71_to_-70.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-70_to_-69.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-69_to_-68.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-68_to_-67.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-67_to_-66.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-66_to_-65.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-65_to_-64.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-64_to_-63.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-63_to_-62.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-62_to_-61.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-61_to_-60.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-60_to_-59.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-59_to_-58.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-58_to_-57.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-57_to_-56.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-56_to_-55.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-55_to_-54.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-54_to_-53.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-53_to_-52.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-52_to_-51.html
✅ Saved: results/dist/kpis_pdf_rsrp_bins/RSRP_-51_to_-50.html

In [1]:
import os
import pandas as pd
import _common, _map, _plot, _dist
device = 'SM-S938N'

df = _common.analyze_kpi(
    fname = os.path.join("logs",f"{device}.xlsx"),
    date_list = [
        # "251016",
        # "251017",
        # "251020",
        # "251021",
        "251022", # pdcch dynamic 적용
        "251023",
        "251024",
        "251027",
        "251103",
        "251105",
    ],
)
rb_min=0
rsrp_bin=1
sample_min=30
grid_size=30

out_dir = os.path.join("results")
_plot.plot_fixed_point(df=df, out_dir=out_dir, rb_min=rb_min, sample_min=sample_min, rsrp_bin=rsrp_bin, grid_size=grid_size)
_plot.plot_fixed_point_apple(df=df, out_dir=out_dir, rb_min=rb_min, sample_min=sample_min, rsrp_bin=rsrp_bin, grid_size=grid_size)

Reading logs/SM-S938N.xlsx
✅ Read Complete : 98536 lines
⚠️ Locations without UHD Power measurements have been removed (dropped: 795, remaining: 40748/41543)
✅ Saved: results/plot_fixed_point/Huam345-5_251024_01.html
✅ Saved: results/plot_fixed_point/Huam345-5_251024_02.html
✅ Saved: results/plot_fixed_point/Huam345-5_251103_01.html
✅ Saved: results/plot_fixed_point/Huam345-5_251103_02.html
✅ Saved: results/plot_fixed_point/Huam345-5_251103_03.html
✅ Saved: results/plot_fixed_point/Namsan_251105_01.html
✅ Saved: results/plot_fixed_point/Namsan_251105_02.html
⚠️ Locations without UHD Power measurements have been removed (dropped: 795, remaining: 40748/41543)
✅ Saved: results/plot_fixed_point/Huam345-5_iPhone16e.html
✅ Saved: results/plot_fixed_point/Namsan_iPhone16e.html

In [2]:
# import os
# import pandas as pd
# import _common, _map, _plot, _dist, _plot_test
# device = 'SM-S938N'

# # grid가 커질수록 GPS 오차 보정 및 통계적 안정성 향상
# # - 이동 속도 약 36 km/h (≈ 10 m/s) 기준, 30m 구간당 약 3개 샘플 수집
# # - 동일 루트 10회 이상 반복 시 grid별 30개 이상 샘플 확보 가능
# # - 샘플 수 30개 이상이면 중심극한정리(CLT)에 따라 정규분포 근사 가능
# # - SINR, Tput 등 고분산 지표의 신뢰구간(CI) 추정에 적합

# rb_min=0
# rsrp_bin=1
# sample_min=0
# grid_size=30

# df_grid = pd.read_excel(os.path.join("logs", f"{device}_grid_{grid_size}m.xlsx"))
# out_dir = os.path.join("results", "plot_test")
# _plot_test.plot_kpis_by_uhd(df=df_grid, out_dir=out_dir, rb_min=rb_min, sample_min=sample_min, rsrp_bin=rsrp_bin, grid_size=grid_size)